#!/bin/bash
# network-setup.sh
# ─────────────────────────────────────────────────────────────────────────────
# Automates Hyperledger Fabric network setup for the voting system.
# Run this AFTER docker-compose up brings up the peers and orderer.
#
# Prerequisites:
#   - fabric-samples downloaded: https://github.com/hyperledger/fabric-samples
#   - FABRIC_SAMPLES_PATH set below
#   - All containers running: docker-compose up -d
#
# Usage:
#   chmod +x network-setup.sh
#   ./network-setup.sh
# ─────────────────────────────────────────────────────────────────────────────

set -e  # Exit on any error

# ── Config ────────────────────────────────────────────────────────────────────
FABRIC_SAMPLES_PATH="${HOME}/fabric-samples"
CHANNEL_NAME="mychannel"
CHAINCODE_NAME="voting"
CHAINCODE_PATH="$(pwd)/chaincode/voting"
CHAINCODE_VERSION="1.0"
CHAINCODE_SEQUENCE="1"

# Peer connection details
PEER0_ORG1="localhost:7051"
PEER0_ORG2="localhost:9051"
ORDERER="localhost:7050"

export PATH="${FABRIC_SAMPLES_PATH}/bin:${PATH}"
export FABRIC_CFG_PATH="${FABRIC_SAMPLES_PATH}/config"

# TLS cert paths (generated by cryptogen/fabric-ca)
ORG1_TLS_CA="$(pwd)/network/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt"
ORG2_TLS_CA="$(pwd)/network/organizations/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt"
ORDERER_TLS_CA="$(pwd)/network/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem"

# MSP paths
ORG1_ADMIN_MSP="$(pwd)/network/organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp"
ORG2_ADMIN_MSP="$(pwd)/network/organizations/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp"

echo "================================================================"
echo "  VOTING SYSTEM — Hyperledger Fabric Network Setup"
echo "================================================================"

# ── Step 1: Generate crypto material ─────────────────────────────────────────
echo ""
echo "Step 1: Generating crypto material..."
if [ ! -d "$(pwd)/network/organizations" ]; then
  cryptogen generate \
    --config="$(pwd)/network/crypto-config.yaml" \
    --output="$(pwd)/network/organizations"
  echo "✅ Crypto material generated."
else
  echo "   Crypto material already exists, skipping."
fi

# ── Step 2: Create genesis block ─────────────────────────────────────────────
echo ""
echo "Step 2: Creating genesis block..."
if [ ! -f "$(pwd)/network/genesis.block" ]; then
  configtxgen \
    -profile TwoOrgsOrdererGenesis \
    -channelID system-channel \
    -outputBlock "$(pwd)/network/genesis.block" \
    -configPath "$(pwd)/network"
  echo "✅ Genesis block created."
fi

# ── Step 3: Create channel transaction ───────────────────────────────────────
echo ""
echo "Step 3: Creating channel transaction..."
if [ ! -f "$(pwd)/network/${CHANNEL_NAME}.tx" ]; then
  configtxgen \
    -profile TwoOrgsChannel \
    -outputCreateChannelTx "$(pwd)/network/${CHANNEL_NAME}.tx" \
    -channelID "${CHANNEL_NAME}" \
    -configPath "$(pwd)/network"
  echo "✅ Channel transaction created."
fi

# ── Step 4: Create channel ────────────────────────────────────────────────────
echo ""
echo "Step 4: Creating channel '${CHANNEL_NAME}'..."
export CORE_PEER_LOCALMSPID="Org1MSP"
export CORE_PEER_MSPCONFIGPATH="${ORG1_ADMIN_MSP}"
export CORE_PEER_ADDRESS="${PEER0_ORG1}"
export CORE_PEER_TLS_ENABLED="true"
export CORE_PEER_TLS_ROOTCERT_FILE="${ORG1_TLS_CA}"

peer channel create \
  -o "${ORDERER}" \
  -c "${CHANNEL_NAME}" \
  -f "$(pwd)/network/${CHANNEL_NAME}.tx" \
  --outputBlock "$(pwd)/network/${CHANNEL_NAME}.block" \
  --ordererTLSHostnameOverride orderer.example.com \
  --tls --cafile "${ORDERER_TLS_CA}"
echo "✅ Channel created."

# ── Step 5: Join peers to channel ────────────────────────────────────────────
echo ""
echo "Step 5: Joining peers to channel..."

# Org1 peer
peer channel join -b "$(pwd)/network/${CHANNEL_NAME}.block"
echo "   ✅ peer0.org1 joined channel."

# Org2 peer
export CORE_PEER_LOCALMSPID="Org2MSP"
export CORE_PEER_MSPCONFIGPATH="${ORG2_ADMIN_MSP}"
export CORE_PEER_ADDRESS="${PEER0_ORG2}"
export CORE_PEER_TLS_ROOTCERT_FILE="${ORG2_TLS_CA}"
peer channel join -b "$(pwd)/network/${CHANNEL_NAME}.block"
echo "   ✅ peer0.org2 joined channel."

# ── Step 6: Package chaincode ─────────────────────────────────────────────────
echo ""
echo "Step 6: Packaging chaincode..."
cd "${CHAINCODE_PATH}" && npm install && cd -
peer lifecycle chaincode package voting.tar.gz \
  --path "${CHAINCODE_PATH}" \
  --lang node \
  --label "${CHAINCODE_NAME}_${CHAINCODE_VERSION}"
echo "✅ Chaincode packaged."

# ── Step 7: Install chaincode on both peers ───────────────────────────────────
echo ""
echo "Step 7: Installing chaincode on peers..."

# Org1
export CORE_PEER_LOCALMSPID="Org1MSP"
export CORE_PEER_MSPCONFIGPATH="${ORG1_ADMIN_MSP}"
export CORE_PEER_ADDRESS="${PEER0_ORG1}"
export CORE_PEER_TLS_ROOTCERT_FILE="${ORG1_TLS_CA}"
peer lifecycle chaincode install voting.tar.gz
echo "   ✅ Installed on peer0.org1"

# Org2
export CORE_PEER_LOCALMSPID="Org2MSP"
export CORE_PEER_MSPCONFIGPATH="${ORG2_ADMIN_MSP}"
export CORE_PEER_ADDRESS="${PEER0_ORG2}"
export CORE_PEER_TLS_ROOTCERT_FILE="${ORG2_TLS_CA}"
peer lifecycle chaincode install voting.tar.gz
echo "   ✅ Installed on peer0.org2"

# Get package ID
PACKAGE_ID=$(peer lifecycle chaincode queryinstalled | grep "${CHAINCODE_NAME}_${CHAINCODE_VERSION}" | sed 's/.*Package ID: //; s/, Label.*//')
echo "   Package ID: ${PACKAGE_ID}"

# ── Step 8: Approve chaincode for both orgs ───────────────────────────────────
echo ""
echo "Step 8: Approving chaincode definition..."

# Org2 approval
peer lifecycle chaincode approveformyorg \
  -o "${ORDERER}" \
  --ordererTLSHostnameOverride orderer.example.com \
  --channelID "${CHANNEL_NAME}" \
  --name "${CHAINCODE_NAME}" \
  --version "${CHAINCODE_VERSION}" \
  --package-id "${PACKAGE_ID}" \
  --sequence "${CHAINCODE_SEQUENCE}" \
  --tls --cafile "${ORDERER_TLS_CA}"
echo "   ✅ Org2 approved."

# Org1 approval
export CORE_PEER_LOCALMSPID="Org1MSP"
export CORE_PEER_MSPCONFIGPATH="${ORG1_ADMIN_MSP}"
export CORE_PEER_ADDRESS="${PEER0_ORG1}"
export CORE_PEER_TLS_ROOTCERT_FILE="${ORG1_TLS_CA}"
peer lifecycle chaincode approveformyorg \
  -o "${ORDERER}" \
  --ordererTLSHostnameOverride orderer.example.com \
  --channelID "${CHANNEL_NAME}" \
  --name "${CHAINCODE_NAME}" \
  --version "${CHAINCODE_VERSION}" \
  --package-id "${PACKAGE_ID}" \
  --sequence "${CHAINCODE_SEQUENCE}" \
  --tls --cafile "${ORDERER_TLS_CA}"
echo "   ✅ Org1 approved."

# ── Step 9: Commit chaincode to channel ──────────────────────────────────────
echo ""
echo "Step 9: Committing chaincode..."
peer lifecycle chaincode commit \
  -o "${ORDERER}" \
  --ordererTLSHostnameOverride orderer.example.com \
  --channelID "${CHANNEL_NAME}" \
  --name "${CHAINCODE_NAME}" \
  --version "${CHAINCODE_VERSION}" \
  --sequence "${CHAINCODE_SEQUENCE}" \
  --tls --cafile "${ORDERER_TLS_CA}" \
  --peerAddresses "${PEER0_ORG1}" \
  --tlsRootCertFiles "${ORG1_TLS_CA}" \
  --peerAddresses "${PEER0_ORG2}" \
  --tlsRootCertFiles "${ORG2_TLS_CA}"
echo "✅ Chaincode committed to channel."

# ── Step 10: Initialize ledger ────────────────────────────────────────────────
echo ""
echo "Step 10: Initializing ledger..."
peer chaincode invoke \
  -o "${ORDERER}" \
  --ordererTLSHostnameOverride orderer.example.com \
  --tls --cafile "${ORDERER_TLS_CA}" \
  -C "${CHANNEL_NAME}" \
  -n "${CHAINCODE_NAME}" \
  --peerAddresses "${PEER0_ORG1}" --tlsRootCertFiles "${ORG1_TLS_CA}" \
  --peerAddresses "${PEER0_ORG2}" --tlsRootCertFiles "${ORG2_TLS_CA}" \
  -c '{"function":"initLedger","Args":[]}'

sleep 3
echo "✅ Ledger initialized."

echo ""
echo "================================================================"
echo "  ✅ Network setup complete!"
echo ""
echo "  Next steps:"
echo "  1. Run backend: cd backend && node seed.js && npm start"
echo "  2. Run frontend: cd frontend && npm start"
echo "  3. On Raspberry Pi: python3 hardware/biometric.py"
echo "================================================================"
